name: Lint & Test & Build

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - development
  push:
    branches:
      - main

env:
  NODE_VERSION: 18.x
  OS: ubuntu-latest

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    with:
      os: $OS
      node-version: $NODE_VERSION

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      os: $OS
      node-version: $NODE_VERSION

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      os: $OS
      node-version: $NODE_VERSION
